In [1]:
import numpy as np
import pandas as pd

In [2]:
dt=pd.read_csv("/Users/sunny/Downloads/Telegram Desktop/Prostate_Cancer.csv")

In [3]:
dt.head()

id diagnosis_result  radius  texture  perimeter  area  smoothness  \
0   1                M      23       12        151   954       0.143   
1   2                B       9       13        133  1326       0.143   
2   3                M      21       27        130  1203       0.125   
3   4                M      14       16         78   386       0.070   
4   5                M       9       19        135  1297       0.141   

   compactness  symmetry  fractal_dimension  
0        0.278     0.242              0.079  
1        0.079     0.181              0.057  
2        0.160     0.207              0.060  
3        0.284     0.260              0.097  
4        0.133     0.181              0.059

In [4]:
dt.isnull().any()

id                   False
diagnosis_result     False
radius               False
texture              False
perimeter            False
area                 False
smoothness           False
compactness          False
symmetry             False
fractal_dimension    False
dtype: bool

In [5]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 100 non-null    int64  
 1   diagnosis_result   100 non-null    object 
 2   radius             100 non-null    int64  
 3   texture            100 non-null    int64  
 4   perimeter          100 non-null    int64  
 5   area               100 non-null    int64  
 6   smoothness         100 non-null    float64
 7   compactness        100 non-null    float64
 8   symmetry           100 non-null    float64
 9   fractal_dimension  100 non-null    float64
dtypes: float64(4), int64(5), object(1)
memory usage: 7.9+ KB


In [13]:
dt["diagnosis_result"].unique()

array(['M', 'B'], dtype=object)

In [14]:
x=dt.iloc[:,2:10].values
y=dt.iloc[:,1:2].values

In [15]:
y.shape

(100, 1)

In [16]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("oh",OneHotEncoder(),[0])],remainder="passthrough")
#coverts data into binary form
y=ct.fit_transform(y)

In [17]:
y

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.

In [18]:
y.shape

(100, 2)

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [20]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [21]:
from tensorflow.keras.models import Sequential #this library is used to initialise the model
from tensorflow.keras.layers import Dense  #used to add layers of ANN

In [22]:
ann=Sequential()

In [23]:
ann.add(Dense(8,kernel_initializer="random_uniform",activation="relu"))

In [24]:
ann.add(Dense(16,kernel_initializer="random_uniform",activation="relu"))

In [25]:
ann.add(Dense(2,kernel_initializer="random_uniform",activation="softmax"))

In [26]:
ann.compile("adam","binary_crossentropy",metrics=["accuracy"])

In [27]:
ann.fit(x_train,y_train,batch_size=32,epochs=20)

Epoch 1/20
3/3 [==============================] - 0s 2ms/step - loss: 0.6931 - accuracy: 0.6023
Epoch 2/20
3/3 [==============================] - 0s 3ms/step - loss: 0.6929 - accuracy: 0.5547
Epoch 3/20
3/3 [==============================] - 0s 5ms/step - loss: 0.6927 - accuracy: 0.5508
Epoch 4/20
3/3 [==============================] - 0s 6ms/step - loss: 0.6926 - accuracy: 0.5430
Epoch 5/20
3/3 [==============================] - 0s 4ms/step - loss: 0.6920 - accuracy: 0.5742
Epoch 6/20
3/3 [==============================] - 0s 6ms/step - loss: 0.6919 - accuracy: 0.5625
Epoch 7/20
3/3 [==============================] - 0s 4ms/step - loss: 0.6917 - accuracy: 0.5547
Epoch 8/20
3/3 [==============================] - 0s 6ms/step - loss: 0.6912 - accuracy: 0.5625
Epoch 9/20
3/3 [==============================] - 0s 5ms/step - loss: 0.6907 - accuracy: 0.5664
Epoch 10/20
3/3 [==============================] - 0s 3ms/step - loss: 0.6907 - accuracy: 0.5469
Epoch 11/20
3/3 [======================

In [28]:
ypred=ann.predict(x_test)

In [29]:
ypred

array([[0.45667213, 0.5433279 ],
       [0.49250975, 0.5074902 ],
       [0.44356588, 0.55643415],
       [0.5039079 , 0.49609208],
       [0.49071318, 0.5092868 ],
       [0.49029863, 0.5097013 ],
       [0.48423573, 0.51576424],
       [0.49377394, 0.50622606],
       [0.49515802, 0.504842  ],
       [0.449154  , 0.550846  ],
       [0.44541103, 0.554589  ],
       [0.5005806 , 0.49941933],
       [0.4089866 , 0.59101343],
       [0.47221968, 0.5277803 ],
       [0.46736413, 0.53263587],
       [0.4348283 , 0.5651717 ],
       [0.4569547 , 0.54304534],
       [0.44375834, 0.55624163],
       [0.43932763, 0.5606724 ],
       [0.46892318, 0.53107685]], dtype=float32)

In [31]:
y_test>0.5

array([[False,  True],
       [False,  True],
       [False,  True],
       [ True, False],
       [False,  True],
       [ True, False],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [ True, False],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True]])

In [32]:
ypred>0.5

array([[False,  True],
       [False,  True],
       [False,  True],
       [ True, False],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [ True, False],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True]])

In [33]:
yp=ann.predict(sc.transform([[23,12,151,954,0.143,0.278,0.242,0.079]]))

In [34]:
yp

array([[0.4254926, 0.5745074]], dtype=float32)

In [35]:
yp>0.5

array([[False,  True]])

In [36]:
#the disagonistic result is M