In [1]:
import numpy as np
import pandas as pd

In [2]:
dt=pd.read_csv("/Users/sunny/Downloads/Telegram Desktop/Bankloan.csv")

In [3]:
dt.head()

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49     91107       4    1.6          1         0   
1   2   45          19      34     90089       3    1.5          1         0   
2   3   39          15      11     94720       1    1.0          1         0   
3   4   35           9     100     94112       1    2.7          2         0   
4   5   35           8      45     91330       4    1.0          2         0   

   Personal Loan  Securities Account  CD Account  Online  CreditCard  
0              0                   1           0       0           0  
1              0                   1           0       0           0  
2              0                   0           0       0           0  
3              0                   0           0       0           0  
4              0                   0           0       0           1

In [4]:
dt.isnull().any()

ID                    False
Age                   False
Experience            False
Income                False
ZIP Code              False
Family                False
CCAvg                 False
Education             False
Mortgage              False
Personal Loan         False
Securities Account    False
CD Account            False
Online                False
CreditCard            False
dtype: bool

In [5]:
dt.drop(columns=["ID","ZIP Code"],inplace=True)

In [6]:
dt.head()

Age  Experience  Income  Family  CCAvg  Education  Mortgage  Personal Loan  \
0   25           1      49       4    1.6          1         0              0   
1   45          19      34       3    1.5          1         0              0   
2   39          15      11       1    1.0          1         0              0   
3   35           9     100       1    2.7          2         0              0   
4   35           8      45       4    1.0          2         0              0   

   Securities Account  CD Account  Online  CreditCard  
0                   1           0       0           0  
1                   1           0       0           0  
2                   0           0       0           0  
3                   0           0       0           0  
4                   0           0       0           1

In [7]:
x=dt.iloc[:,[0,1,2,3,4,5,6,8,9,10,11]].values
y=dt.iloc[:,7].values

In [8]:
y

array([0, 0, 0, ..., 0, 0, 0])

In [9]:
x

array([[25.,  1., 49., ...,  0.,  0.,  0.],
       [45., 19., 34., ...,  0.,  0.,  0.],
       [39., 15., 11., ...,  0.,  0.,  0.],
       ...,
       [63., 39., 24., ...,  0.,  0.,  0.],
       [65., 40., 49., ...,  0.,  1.,  0.],
       [28.,  4., 83., ...,  0.,  1.,  1.]])

In [10]:
x.shape

(5000, 11)

In [11]:
y.shape

(5000,)

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [13]:
x_train.shape

(4000, 11)

In [14]:
y_train.shape

(4000,)

In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [16]:
x_test

array([[ 0.75382635,  0.86891925, -1.10906256, ..., -0.2503982 ,
        -1.23759669, -0.64842466],
       [-1.09616235, -0.98755691,  0.22453305, ..., -0.2503982 ,
         0.80801767, -0.64842466],
       [ 0.75382635,  0.33849749, -0.01995948, ..., -0.2503982 ,
        -1.23759669,  1.5421992 ],
       ...,
       [ 1.10620515,  1.22253375, -1.39800827, ..., -0.2503982 ,
        -1.23759669, -0.64842466],
       [ 0.75382635,  0.69211199, -0.46449135, ..., -0.2503982 ,
         0.80801767, -0.64842466],
       [-0.47949945, -0.54553878, -0.26445201, ..., -0.2503982 ,
         0.80801767, -0.64842466]])

In [17]:
x_train

array([[-0.54939992, -0.70298746,  0.02175233, ..., -0.25432119,
         0.82545668,  1.55150089],
       [-1.1586596 , -1.05065683, -0.19431256, ..., -0.25432119,
         0.82545668, -0.64453717],
       [ 1.71356461,  1.64378077, -1.10178513, ..., -0.25432119,
        -1.21145061,  1.55150089],
       ...,
       [-1.68088218, -1.65907822, -1.08017864, ..., -0.25432119,
        -1.21145061,  1.55150089],
       [ 1.01726783,  1.12227672, -0.5400164 , ...,  3.93203578,
         0.82545668,  1.55150089],
       [-1.0716225 , -0.96373949, -0.77768778, ..., -0.25432119,
        -1.21145061, -0.64453717]])

In [18]:
from tensorflow.keras.models import Sequential #this library is used to initialise the model
from tensorflow.keras.layers import Dense  #used to add layers of ANN

In [19]:
ann=Sequential()

In [20]:
ann.add(Dense(11,kernel_initializer="random_uniform",activation="relu"))

In [21]:
ann.add(Dense(22,kernel_initializer="random_uniform",activation="relu"))

In [22]:
ann.add(Dense(1,kernel_initializer="random_uniform",activation="sigmoid"))

In [23]:
ann.compile("adam","binary_crossentropy",metrics=["accuracy"])

In [24]:
ann.fit(x_train,y_train,batch_size=32,epochs=25)

Epoch 1/25
125/125 [==============================] - 1s 986us/step - loss: 0.6382 - accuracy: 0.8738
Epoch 2/25
125/125 [==============================] - 0s 1ms/step - loss: 0.2309 - accuracy: 0.8923
Epoch 3/25
125/125 [==============================] - 0s 1ms/step - loss: 0.1628 - accuracy: 0.9074
Epoch 4/25
125/125 [==============================] - 0s 996us/step - loss: 0.1466 - accuracy: 0.9003
Epoch 5/25
125/125 [==============================] - 0s 1ms/step - loss: 0.1230 - accuracy: 0.9557
Epoch 6/25
125/125 [==============================] - 0s 997us/step - loss: 0.1028 - accuracy: 0.9655
Epoch 7/25
125/125 [==============================] - 0s 1ms/step - loss: 0.0863 - accuracy: 0.9731
Epoch 8/25
125/125 [==============================] - 0s 1ms/step - loss: 0.0764 - accuracy: 0.9773
Epoch 9/25
125/125 [==============================] - 0s 960us/step - loss: 0.0756 - accuracy: 0.9774
Epoch 10/25
125/125 [==============================] - 0s 1ms/step - loss: 0.0689 - accuracy

In [25]:
ypred=ann.predict(x_test)

In [26]:
ypred=ypred>0.5

In [27]:
ypred

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [

In [28]:
y_test>0.5

array([False, False, False, False, False, False,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [40]:
yp=ann.predict(sc.transform([[19,34,90089,1.5,1,0,0,0,1,0,0]]))

In [41]:
yp

array([[0.9864478]], dtype=float32)

In [43]:
yp>0.5

array([[ True]])

In [ ]:
#bank loan will be given