In [1]:
import numpy as np
import pandas as pd

In [2]:
dt=pd.read_csv("/Users/sunny/Downloads/Telegram Desktop/insurance.csv")

In [3]:
dt.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
dt.isnull().any()

age         False
sex         False
bmi         False
children    False
smoker      False
region      False
charges     False
dtype: bool

In [5]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [6]:
dt["region"].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [12]:
dt["smoker"].unique()

array(['yes', 'no'], dtype=object)

In [13]:
dt["sex"].unique()

array(['female', 'male'], dtype=object)

In [7]:
x=dt.iloc[:,0:6].values
y=dt.iloc[:,6].values

In [8]:
x.shape

(1338, 6)

In [9]:
y.shape

(1338,)

In [10]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("oh",OneHotEncoder(),[1,4,5])],remainder="passthrough")
#coverts data into binary form
x=ct.fit_transform(x)

In [11]:
x.shape

(1338, 11)

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [15]:
x_train

array([[0.0, 1.0, 0.0, ..., 37, 34.1, 4],
       [0.0, 1.0, 1.0, ..., 18, 34.43, 0],
       [1.0, 0.0, 0.0, ..., 23, 36.67, 2],
       ...,
       [0.0, 1.0, 1.0, ..., 40, 25.08, 0],
       [0.0, 1.0, 1.0, ..., 19, 35.53, 0],
       [1.0, 0.0, 1.0, ..., 33, 18.5, 1]], dtype=object)

In [16]:
y_train

array([40182.246 ,  1137.4697, 38511.6283, ...,  5415.6612,  1646.4297,
        4766.022 ])

In [17]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [19]:
ann=Sequential()

In [20]:
ann.add(Dense(6,kernel_initializer="random_uniform",activation="relu"))

In [21]:
ann.add(Dense(12,kernel_initializer="random_uniform",activation="relu"))

In [22]:
ann.add(Dense(1,kernel_initializer="random_uniform",activation="relu"))

In [23]:
ann.compile("adam","mean_squared_error",metrics=["accuracy"])

In [24]:
ann.fit(x_train,y_train,batch_size=32,epochs=500)

Epoch 1/500
34/34 [==============================] - 0s 1ms/step - loss: 305239748.5714 - accuracy: 0.0000e+00
Epoch 2/500
34/34 [==============================] - 0s 1ms/step - loss: 313756637.7143 - accuracy: 0.0000e+00
Epoch 3/500
34/34 [==============================] - 0s 1ms/step - loss: 335383839.0857 - accuracy: 0.0000e+00
Epoch 4/500
34/34 [==============================] - 0s 1ms/step - loss: 318609605.4857 - accuracy: 0.0000e+00
Epoch 5/500
34/34 [==============================] - 0s 1ms/step - loss: 324510427.4286 - accuracy: 0.0000e+00
Epoch 6/500
34/34 [==============================] - 0s 2ms/step - loss: 314553133.7143 - accuracy: 0.0000e+00
Epoch 7/500
34/34 [==============================] - 0s 1ms/step - loss: 304456850.7429 - accuracy: 0.0000e+00
Epoch 8/500
34/34 [==============================] - 0s 1ms/step - loss: 300282640.9143 - accuracy: 0.0000e+00
Epoch 9/500
34/34 [==============================] - 0s 1ms/step - loss: 315206549.0286 - accuracy: 0.0000e+00
E

34/34 [==============================] - 0s 1ms/step - loss: 176503465.1429 - accuracy: 0.0000e+00
Epoch 75/500
34/34 [==============================] - 0s 1ms/step - loss: 177228787.6571 - accuracy: 0.0000e+00
Epoch 76/500
34/34 [==============================] - 0s 1ms/step - loss: 174616961.1429 - accuracy: 0.0000e+00
Epoch 77/500
34/34 [==============================] - 0s 1ms/step - loss: 167746087.3143 - accuracy: 0.0000e+00
Epoch 78/500
34/34 [==============================] - 0s 1ms/step - loss: 166160274.2857 - accuracy: 0.0000e+00
Epoch 79/500
34/34 [==============================] - 0s 1ms/step - loss: 157308963.6571 - accuracy: 0.0000e+00
Epoch 80/500
34/34 [==============================] - 0s 1ms/step - loss: 157281999.3143 - accuracy: 0.0000e+00
Epoch 81/500
34/34 [==============================] - 0s 1ms/step - loss: 164399337.6000 - accuracy: 0.0000e+00
Epoch 82/500
34/34 [==============================] - 0s 1ms/step - loss: 157457038.1714 - accuracy: 0.0000e+00
Epoch

34/34 [==============================] - 0s 1ms/step - loss: 47899792.3429 - accuracy: 0.0000e+00
Epoch 148/500
34/34 [==============================] - 0s 1ms/step - loss: 45830685.0286 - accuracy: 0.0000e+00
Epoch 149/500
34/34 [==============================] - 0s 1ms/step - loss: 46537043.2000 - accuracy: 0.0000e+00
Epoch 150/500
34/34 [==============================] - 0s 1ms/step - loss: 46488072.1143 - accuracy: 0.0000e+00
Epoch 151/500
34/34 [==============================] - 0s 1ms/step - loss: 44991682.3429 - accuracy: 0.0000e+00
Epoch 152/500
34/34 [==============================] - 0s 1ms/step - loss: 44683337.6000 - accuracy: 0.0000e+00
Epoch 153/500
34/34 [==============================] - 0s 1ms/step - loss: 46869139.8857 - accuracy: 0.0000e+00
Epoch 154/500
34/34 [==============================] - 0s 1ms/step - loss: 40752545.6000 - accuracy: 0.0000e+00
Epoch 155/500
34/34 [==============================] - 0s 1ms/step - loss: 48293343.7714 - accuracy: 0.0000e+00
Epoch 

34/34 [==============================] - 0s 1ms/step - loss: 33599467.5429 - accuracy: 0.0000e+00
Epoch 221/500
34/34 [==============================] - 0s 1ms/step - loss: 36212822.6857 - accuracy: 0.0000e+00
Epoch 222/500
34/34 [==============================] - 0s 1ms/step - loss: 37511460.2857 - accuracy: 0.0000e+00
Epoch 223/500
34/34 [==============================] - 0s 1ms/step - loss: 35885136.2857 - accuracy: 0.0000e+00
Epoch 224/500
34/34 [==============================] - 0s 1ms/step - loss: 31309835.2571 - accuracy: 0.0000e+00
Epoch 225/500
34/34 [==============================] - 0s 1ms/step - loss: 36973904.2857 - accuracy: 0.0000e+00
Epoch 226/500
34/34 [==============================] - 0s 1ms/step - loss: 35745794.6857 - accuracy: 0.0000e+00
Epoch 227/500
34/34 [==============================] - 0s 1ms/step - loss: 39765828.9143 - accuracy: 0.0000e+00
Epoch 228/500
34/34 [==============================] - 0s 1ms/step - loss: 33842004.8000 - accuracy: 0.0000e+00
Epoch 

34/34 [==============================] - 0s 2ms/step - loss: 32892342.1714 - accuracy: 0.0000e+00
Epoch 294/500
34/34 [==============================] - 0s 2ms/step - loss: 35941581.8286 - accuracy: 0.0000e+00
Epoch 295/500
34/34 [==============================] - 0s 1ms/step - loss: 34114769.2000 - accuracy: 0.0000e+00
Epoch 296/500
34/34 [==============================] - 0s 1ms/step - loss: 34099560.1143 - accuracy: 0.0000e+00
Epoch 297/500
34/34 [==============================] - 0s 1ms/step - loss: 32308204.7429 - accuracy: 0.0000e+00
Epoch 298/500
34/34 [==============================] - 0s 943us/step - loss: 31281724.8000 - accuracy: 0.0000e+00
Epoch 299/500
34/34 [==============================] - 0s 1ms/step - loss: 33323765.6000 - accuracy: 0.0000e+00
Epoch 300/500
34/34 [==============================] - 0s 1ms/step - loss: 33629705.0286 - accuracy: 0.0000e+00
Epoch 301/500
34/34 [==============================] - 0s 1ms/step - loss: 34963371.5429 - accuracy: 0.0000e+00
Epoc

34/34 [==============================] - 0s 1ms/step - loss: 32276809.0857 - accuracy: 0.0000e+00
Epoch 367/500
34/34 [==============================] - 0s 1ms/step - loss: 34115213.0286 - accuracy: 0.0000e+00
Epoch 368/500
34/34 [==============================] - 0s 1ms/step - loss: 33897913.0286 - accuracy: 0.0000e+00
Epoch 369/500
34/34 [==============================] - 0s 1ms/step - loss: 37325687.0286 - accuracy: 0.0000e+00
Epoch 370/500
34/34 [==============================] - 0s 1ms/step - loss: 31757463.7714 - accuracy: 0.0000e+00
Epoch 371/500
34/34 [==============================] - 0s 1ms/step - loss: 32479026.2857 - accuracy: 0.0000e+00
Epoch 372/500
34/34 [==============================] - 0s 2ms/step - loss: 31395657.6571 - accuracy: 0.0000e+00
Epoch 373/500
34/34 [==============================] - 0s 2ms/step - loss: 37534888.0000 - accuracy: 0.0000e+00
Epoch 374/500
34/34 [==============================] - 0s 1ms/step - loss: 34484802.2286 - accuracy: 0.0000e+00
Epoch 

34/34 [==============================] - 0s 1ms/step - loss: 32623516.0571 - accuracy: 0.0000e+00
Epoch 440/500
34/34 [==============================] - 0s 1ms/step - loss: 32152074.8571 - accuracy: 0.0000e+00
Epoch 441/500
34/34 [==============================] - 0s 1ms/step - loss: 37897117.7714 - accuracy: 0.0000e+00
Epoch 442/500
34/34 [==============================] - 0s 1ms/step - loss: 32510290.0571 - accuracy: 0.0000e+00
Epoch 443/500
34/34 [==============================] - 0s 1ms/step - loss: 37100863.6571 - accuracy: 0.0000e+00
Epoch 444/500
34/34 [==============================] - 0s 1ms/step - loss: 32752555.4286 - accuracy: 0.0000e+00
Epoch 445/500
34/34 [==============================] - 0s 1ms/step - loss: 34492183.5429 - accuracy: 0.0000e+00
Epoch 446/500
34/34 [==============================] - 0s 1ms/step - loss: 32297806.3429 - accuracy: 0.0000e+00
Epoch 447/500
34/34 [==============================] - 0s 1ms/step - loss: 32139619.6000 - accuracy: 0.0000e+00
Epoch 

In [25]:
ypred=ann.predict(x_test)

In [26]:
ypred

array([[ 9722.339  ],
       [ 9268.21   ],
       [44359.266  ],
       [16745.285  ],
       [ 5808.318  ],
       [ 2990.4517 ],
       [ 3102.851  ],
       [13587.832  ],
       [ 8853.907  ],
       [ 7083.1772 ],
       [ 5041.891  ],
       [ 9320.995  ],
       [ 9851.161  ],
       [ 4287.4067 ],
       [26091.557  ],
       [10355.881  ],
       [ 8096.3706 ],
       [ 6217.6987 ],
       [ 7128.723  ],
       [24868.664  ],
       [33284.008  ],
       [13295.113  ],
       [12413.31   ],
       [31637.395  ],
       [ 4759.8013 ],
       [ 9300.796  ],
       [ 1842.1859 ],
       [ 9869.491  ],
       [ 4430.089  ],
       [ 8491.593  ],
       [ 8678.288  ],
       [47240.52   ],
       [15932.653  ],
       [13923.046  ],
       [19353.148  ],
       [ 5957.7114 ],
       [11277.253  ],
       [32408.242  ],
       [35056.2    ],
       [ 6361.531  ],
       [ 4267.767  ],
       [ 3578.0667 ],
       [28685.84   ],
       [45316.164  ],
       [27741.395  ],
       [ 6

In [27]:
y_test

array([ 9724.53    ,  8547.6913  , 45702.02235 , 12950.0712  ,
        9644.2525  ,  4500.33925 ,  2198.18985 , 11436.73815 ,
        7537.1639  ,  5425.02335 ,  6753.038   , 10493.9458  ,
        7337.748   ,  4185.0979  , 18310.742   , 10702.6424  ,
       12523.6048  ,  3490.5491  ,  6457.8434  , 33475.81715 ,
       23967.38305 , 12643.3778  , 23045.56616 , 23065.4207  ,
        1674.6323  ,  4667.60765 ,  3732.6251  ,  7682.67    ,
        3756.6216  ,  8413.46305 ,  8059.6791  , 48970.2476  ,
       12979.358   , 20630.28351 , 14571.8908  ,  4137.5227  ,
        8347.1643  , 51194.55914 , 40003.33225 ,  1880.487   ,
        5458.04645 ,  2867.1196  , 20149.3229  , 47496.49445 ,
       36149.4835  , 26018.95052 , 19749.38338 ,  6940.90985 ,
        4718.20355 , 22192.43711 ,  2899.48935 , 18838.70366 ,
       23568.272   , 46255.1125  , 24227.33724 ,  3268.84665 ,
        2322.6218  ,  8827.2099  , 14478.33015 , 13112.6048  ,
        1253.936   , 46718.16325 , 13919.8229  ,  9630.

In [30]:
yp=ann.predict(sc.transform(ct.transform([[18,"male",33.00,0,"no","southeast"]])))

In [31]:
yp

array([[4064.0842]], dtype=float32)